### PR TITLE
Update dependencies

### LINKED ISSUE #1: Update outdated dependencies
Please help me update outdated dependencies in the Gem file

### PR DESCRIPTION
**Pull request by BerkhanBerkdemir**
Hey @eddrichjanzzenang 

This PR resolves #1 (yay this is your first issue).

### CODE REVIEW

**Comment by BerkhanBerkdemir** [comment]
@eddrichjanzzenang 

This deprecation says that SQLite changes how to store a boolean.

<details>
<summary>Deprecation warning</summary>

```
DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs

  ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
  ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)

for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file:

Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true
 (called from <main> at alpha-blog/test/test_helper.rb:3)
Run options: --seed 16009
```

</details>

**Comment by BerkhanBerkdemir** [comment]
This PR is ready to merge. You can test this application with `bundle exec rails test`.

**Comment by eddrichjanzzenang** [comment]
Thanks!

**Comment by BerkhanBerkdemir** [comment]
@eddrichjanzzenang could you add label for `hacktoberfest`?

**Pull request merged**
